unbind y 
bind y run "tmux save-buffer - | xsel -ib" \; display "Copied to the system clipboard"

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# jianglai's config

# mouse support
set -g mouse on

# color
set -g default-terminal "xterm-256color"
set -sa terminal-features ",xterm-256color:RGB"

# clipboard
set -s set-clipboard on
set -sa terminal-features ",xterm-256color:clipboard"

# renumber window sequentially when one is closed
set -g renumber-windows on

# vi copy mode
setw -g mode-keys vi

# make ESC instant to accomodate bash vi mode
set -s escape-time 0

# navigate panes (no wrap-around)
bind h if -F '#{pane_at_left}' 'display-panes' { select-pane -L; display-panes }
bind j if -F '#{pane_at_bottom}' 'display-panes' { select-pane -D; display-panes }
bind k if -F '#{pane_at_top}' 'display-panes' { select-pane -U; display-panes }
bind l if -F '#{pane_at_right}' 'display-panes' { select-pane -R; display-panes }
unbind Left
unbind Down
unbind Up
unbind Right

# customize pane colors to indicate active and inactive panes
set -g display-panes-time 500
set -g display-panes-active-colour green
set -g display-panes-colour color238

# customize bottom bar
set -g status-left-length 32
set -g status-left '#{?pane_in_mode,#[reverse] COPY #[noreverse] ,}[#S] '
set -g window-status-current-format '#[bold]#I:#W*'

