# history limit
set -g history-limit 500000
# mouse support
set -g mouse on
# clipboard
set -s set-clipboard on
# make ESC instant
set -s escape-time 0
# Enable RGB colour if running in xterm(1)
set-option -sa terminal-features ",xterm*:RGB"
# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"
# No bells at all
set -g bell-action none

# vi copy mode
setw -g mode-keys vi

# navigate panes (no wrap-around)
bind h if -F '#{pane_at_left}' 'display-panes' { select-pane -L; display-panes }
bind j if -F '#{pane_at_bottom}' 'display-panes' { select-pane -D; display-panes }
bind k if -F '#{pane_at_top}' 'display-panes' { select-pane -U; display-panes }
bind l if -F '#{pane_at_right}' 'display-panes' { select-pane -R; display-panes }
unbind Left
unbind Down
unbind Up
unbind Right

# customize pane colors to indicate active and inactive panes
set -g display-panes-time 500
set -g display-panes-active-colour green
set -g display-panes-colour color238

# customize bottom bar
set -g status-left-length 32
set -g status-left '[#S] '
set -g window-status-current-format '#[bold]#I:#W*'

